### PR TITLE
cross cluser search support, copy of zk index filter branch

### PR DESCRIPTION
**Pull request by rbkasat**

### CODE REVIEW

**Comment by rbkasat** [comment]
@sscarduzio , I just tried to copy all of your code from zk_index_filter branch and created this pull request, not sure why code validation succeeding in your branch and fails in my checkin.

**Comment by rbkasat** [comment]
@sscarduzio any comment?

**Comment by sscarduzio** [comment]
Cool, have you tested this in cross cluster searches?

**Comment by rbkasat** [comment]
yes, its working fine in my cluster currently.

**Comment by rbkasat** [comment]
thanks @sscarduzio

**Pull request merged**
