### PR TITLE
[RORDEV-619] ES 8.0.0 support

### PR DESCRIPTION
**Pull request by coutoPL**
🚀New (ES) New Support for 8.0.0

### CODE REVIEW

**Comment by sscarduzio** [comment]
Did you manage to bypass the authentication header issue?

**Comment by coutoPL** [comment]
@sscarduzio hmm, the PR is related to ES 8.0.0 support. The issue you are talking about is the ECK support task.

**Comment by sscarduzio** [comment]
Yeah true. I mixed the two because in my mind there's the idea of lifting the requirement of disabling xpack security at a certain point

**Comment by sscarduzio** [comment]
I copied over the entire ci/ directory from my branch (where it works), and here it doesn't work. 
Seems that in your "coutoPL/*" branches you don't have the S3 credentials. In the PR I made from "sscarduzio/*" I have.

**Pull request merged**
