### PR TITLE
fixed: ldap group authorization bug

### PR DESCRIPTION
**Pull request by coutoPL**
when LDAP returned no group, user was authorized

### CODE REVIEW

**Comment by sscarduzio** [comment]
this was failing because the gradle bug of 5.4, will merge anyway. Thanks @coutoPL!

**Comment by sscarduzio** [comment]
Shit I closed this as a mistake and I can't merge it anymore.

**Comment by coutoPL** [comment]
you cannot reopen it?

**Comment by sscarduzio** [comment]
OK now I can, just not right away for some reason

**Comment by coutoPL** [comment]
Ok, know why. I haven't noticed that PR is closed instead of merged and I clicked "delete fork branch". And when you wrote that you had made a mistake, I have restored it.

**Pull request merged**
