### PR TITLE
RORDEV-14 [ES] X-Pack's SqlQueryRequest extracts no indices (impacts Kibana Canvas users)

### PR DESCRIPTION
**Pull request by coutoPL**
New (ES) Elasticsearch SQL Support

### CODE REVIEW

**Comment by sscarduzio** [comment]
had a look at this, pretty hardcore! :) 🔝

**Comment by coutoPL** [comment]
> had a look at this, pretty hardcore! :) 🔝

yes, hackish as ... 
Sadly, seems that this is the only possible solution. Good thing is that, everything works like a charm :) Now, have to port it to other ES modules.

**Comment by coutoPL** [comment]
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/496

**Comment by coutoPL** [comment]
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/395

**Pull request merged**
