### PR TITLE
bump circe

### PR DESCRIPTION
**Pull request by clutroth**

### CODE REVIEW

**Comment by sscarduzio** [comment]
does this fix RODEV-244?

**Comment by clutroth** [comment]
I don't think so. I have used newer circe in RORDEV196, so I decided to resolve bump independently. After all there was no issue, but our tests depends on specific behavior of circe 0.11. It  shouldn't have effect on plugin functionality.

**Comment by coutoPL** [comment]
why separate PR for this?

**Comment by clutroth** [comment]
Because circe upgrade failed tests, and I wanted to resolve it in isolation.

**Comment by coutoPL** [comment]
ok, please close when it's not needed any more

**Pull request closed without merging**
